<a href="https://colab.research.google.com/github/Secatorrez/uouw_py_ml/blob/main/kawalki_na_boku.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
def my_function(*kids):
	ile = len(kids)
	#print(ile)
	print("The youngest child is " + kids[ile-1])

my_function("Emil", "Tobias", "Linus", "Najmlodszy")

The youngest child is Najmlodszy


In [ ]:
# tescik array z numpy i zamiana w macierz
import numpy as np
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
a3 = np.array([7,8,9])
amatrix = np.block([[a1], [a2], [a3]])
print(amatrix)
print(amatrix[0])
print(amatrix[1])
print(amatrix[2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[4 5 6]
[7 8 9]


---
**TTTTT**


---



In [ ]:
from math import sqrt, pi

radius = 3.5
area = pi * sqrt(radius)
area1 = pi * radius *radius

print("Promień:", radius)
print("Powierzchnia:", area)
print("Powierzchnia1:", area1)

Promień: 3.5
Powierzchnia: 5.877381679269498
Powierzchnia1: 38.48451000647496


In [ ]:
intchars = ["1", "5", "4"]

newlist = [float(x) for x in intchars]

print(newlist)

[1.0, 5.0, 4.0]
